export default function DocsIndexPage() {
  return (
    <div
      className="markdown-body"
      style={{ animation: "fadeIn 0.5s ease-out" }}
    >
      <h1
        className="page-title text-gradient"
        style={{ fontSize: "2.5rem", marginBottom: "var(--spacing-4)" }}
      >
        HLBW.org Documentation
      </h1>
      <p
        style={{
          fontSize: "1.1rem",
          color: "var(--text-secondary)",
          lineHeight: "1.6",
          marginBottom: "var(--spacing-6)",
        }}
      >
        Welcome to the HLBW AI Hub documentation registry. This section is
        automatically generated by parsing the markdown files within the
        internal repository.
      </p>

      <div
        style={{
          padding: "var(--spacing-6)",
          backgroundColor: "var(--bg-secondary)",
          borderRadius: "var(--border-radius-lg)",
          border: "1px solid var(--border-color)",
        }}
      >
        <h3
          style={{
            fontSize: "1.2rem",
            color: "var(--text-primary)",
            marginBottom: "var(--spacing-3)",
            fontWeight: 600,
          }}
        >
          How to Navigate
        </h3>
        <p
          style={{
            color: "var(--text-secondary)",
            marginBottom: "var(--spacing-4)",
          }}
        >
          Use the left-hand sidebar to explore:
        </p>
        <ul
          style={{
            paddingLeft: "var(--spacing-6)",
            color: "var(--text-secondary)",
            display: "flex",
            flexDirection: "column",
            gap: "var(--spacing-2)",
          }}
        >
          <li>
            <strong>Architecture Guidelines:</strong> High-level system swarming
            models.
          </li>
          <li>
            <strong>Features:</strong> Specific documentation on AI hub
            components.
          </li>
          <li>
            <strong>MCPs:</strong> Context on Model Context Protocol servers.
          </li>
        </ul>
      </div>
    </div>
  );
}
